using System;
using Project001.Gameplay.Levels;
using Project001.Gameplay.Presentation;
using UnityEngine;

namespace Project001.Gameplay.Pixels
{
    /// <summary>
    /// Generates a centred grid of PixelCell objects from a PixelLayoutDefinition,
    /// using a single shared runtime-generated 1x1 sprite. Dimensions and per-cell
    /// MatchTypeId/MatchId come entirely from the injected layout; visual colour
    /// is resolved directly from each cell's own MatchId via
    /// ColorPalette.TryGetByMatchId — the same permanent Match ID -&gt;
    /// canonical colour source CharacterDatabase resolves a collector's
    /// Character_XX prefab from, so a pixel and the collector meant to eat it
    /// always agree on colour by construction. No injected/caller-supplied
    /// colour mapping any more (see MatchTypePresentation's removal) — there
    /// is exactly one presentation colour source in the project now.
    /// </summary>
    public class PixelGrid : MonoBehaviour
    {
        [SerializeField, Tooltip("Preferred (design-target) world-space size of a single square cell, used as-is whenever the grid fits within maxGridWorldWidth/Height at this size. Never exceeded — a small/sparse grid renders at exactly this size instead of being enlarged to fill the field.")]
        [Min(0.001f)]
        private float preferredCellSize = 0.45f;

        [SerializeField, Tooltip("Preferred (design-target) gap between neighbouring cells, in world units. Scaled down by the exact same factor as preferredCellSize whenever the grid must shrink to fit, so the gap-to-cell ratio stays visually consistent at every grid density.")]
        [Min(0f)]
        private float preferredGap = 0.05f;

        [SerializeField, Tooltip("Scene-owned maximum world-space width this grid may occupy. Set by scene layout (e.g. BootstrapSceneCreator) or at runtime via SetFieldBounds before Initialize — not by level data, never referenced by ConveyorSystem or any other gameplay system.")]
        [Min(0f)]
        private float maxGridWorldWidth = 6f;

        [SerializeField, Tooltip("Scene-owned maximum world-space height this grid may occupy. Set by scene layout (e.g. BootstrapSceneCreator) or at runtime via SetFieldBounds before Initialize — not by level data, never referenced by ConveyorSystem or any other gameplay system.")]
        [Min(0f)]
        private float maxGridWorldHeight = 6f;

        private Texture2D _sharedTexture;
        private Sprite _sharedSprite;
        private PixelCell[,] _cells;
        private int _remainingPixelCount;
        private bool _isInitialized;

        public int Width { get; private set; }

        public int Height { get; private set; }

        /// <summary>
        /// The actual world-space size of one square cell, resolved by
        /// Initialize from preferredCellSize scaled down (never up) to fit
        /// maxGridWorldWidth/Height — see TryComputeCellMetrics. Zero before
        /// Initialize succeeds. Purely a presentation metric: exposed so
        /// dependents (e.g. PixelConsumer's alignment tolerance) can derive
        /// their own world-space behaviour from the grid's real runtime
        /// scale instead of duplicating preferredCellSize/preferredGap as
        /// separate constants.
        /// </summary>
        public float CellSize { get; private set; }

        /// <summary>
        /// The actual world-space gap between neighbouring cells, resolved
        /// by the same scale factor as CellSize. Zero before Initialize
        /// succeeds.
        /// </summary>
        public float CellGap { get; private set; }

        /// <summary>
        /// Centre-to-centre world-space distance between neighbouring
        /// cells (CellSize + CellGap) — the same "spacing" GenerateGrid
        /// places cells apart by.
        /// </summary>
        public float CellSpacing => CellSize + CellGap;

        /// <summary>
        /// Number of pixels not yet consumed. Maintained incrementally —
        /// initialized once when the grid is generated and decremented
        /// exactly once per successful consumption. Never rescanned.
        /// </summary>
        public int RemainingPixelCount => _remainingPixelCount;

        /// <summary>
        /// True once every pixel generated by this grid has been consumed.
        /// Purely a state query — this class makes no gameplay decisions
        /// based on it.
        /// </summary>
        public bool IsComplete => _remainingPixelCount <= 0;

        /// <summary>
        /// Sets the world-space field this grid may occupy. Scene-owned
        /// presentation data, exactly like the maxGridWorldWidth/Height
        /// Inspector fields it overwrites — never level data. Exists as a
        /// public seam (instead of only an editor-time SerializedObject
        /// write, see BootstrapSceneCreator) so a future responsive layout
        /// pass can compute bounds from the real screen/safe area at
        /// runtime without reaching past this class's encapsulation. Must
        /// be called before Initialize; calling it afterwards has no effect
        /// on the already-generated grid and is refused (logged).
        /// </summary>
        public void SetFieldBounds(float maxWidth, float maxHeight)
        {
            if (_isInitialized)
            {
                Debug.LogError($"PixelGrid: SetFieldBounds called on '{name}' after Initialize; the grid is already generated at its old bounds. Call SetFieldBounds before Initialize.", this);
                return;
            }

            maxGridWorldWidth = maxWidth;
            maxGridWorldHeight = maxHeight;
        }

        /// <summary>
        /// Builds this grid's cells from the given layout. Must be called
        /// exactly once, before any consumption is attempted. A second call,
        /// or a first call on an object that already has stale baked
        /// children, is refused (logged) rather than generating duplicate
        /// cells. Existing children are never deleted.
        /// </summary>
        public void Initialize(PixelLayoutDefinition layout)
        {
            if (layout == null)
                throw new ArgumentNullException(nameof(layout));

            if (_isInitialized)
            {
                Debug.LogError($"PixelGrid: Initialize called more than once on '{name}'; ignoring to avoid duplicate cells.", this);
                return;
            }

            if (transform.childCount > 0)
            {
                Debug.LogError($"PixelGrid: '{name}' already has {transform.childCount} child object(s) before Initialize; aborting to avoid duplicate cells. Scene may contain stale baked children.", this);
                return;
            }

            if (!TryComputeCellMetrics(layout, out float cellSize, out float gap))
                return;

            CellSize = cellSize;
            CellGap = gap;

            CreateSharedSprite();
            GenerateGrid(layout, cellSize, gap);
            _isInitialized = true;
        }

        /// <summary>
        /// Computes this grid's actual, uniform square cell size and gap: the
        /// natural size layout's dimensions would occupy at preferredCellSize/
        /// preferredGap, scaled down by one uniform factor — never up — only
        /// as much as needed to fit inside maxGridWorldWidth x
        /// maxGridWorldHeight. cellSize and gap are always scaled by the
        /// exact same factor, so the gap-to-cell ratio stays visually
        /// consistent at every density, and a grid small enough to fit at
        /// preferredCellSize renders at exactly that size (scale 1) rather
        /// than being enlarged to fill the field. Fails cleanly — logging one
        /// specific diagnostic and generating nothing — if the bounds,
        /// preferred size, or resulting scale are not positive, rather than
        /// building a partially-sized grid.
        /// </summary>
        private bool TryComputeCellMetrics(PixelLayoutDefinition layout, out float cellSize, out float gap)
        {
            cellSize = 0f;
            gap = 0f;

            if (maxGridWorldWidth <= 0f)
            {
                Debug.LogError($"PixelGrid: '{name}' has a non-positive maxGridWorldWidth ({maxGridWorldWidth}); aborting to avoid generating an invalid grid.", this);
                return false;
            }

            if (maxGridWorldHeight <= 0f)
            {
                Debug.LogError($"PixelGrid: '{name}' has a non-positive maxGridWorldHeight ({maxGridWorldHeight}); aborting to avoid generating an invalid grid.", this);
                return false;
            }

            if (preferredCellSize <= 0f)
            {
                Debug.LogError($"PixelGrid: '{name}' has a non-positive preferredCellSize ({preferredCellSize}); aborting to avoid generating an invalid grid.", this);
                return false;
            }

            float naturalWidth = layout.Width * preferredCellSize + (layout.Width - 1) * preferredGap;
            float naturalHeight = layout.Height * preferredCellSize + (layout.Height - 1) * preferredGap;

            float widthFit = maxGridWorldWidth / naturalWidth;
            float heightFit = maxGridWorldHeight / naturalHeight;
            float scale = Mathf.Min(1f, Mathf.Min(widthFit, heightFit));

            if (scale <= 0f)
            {
                Debug.LogError($"PixelGrid: '{name}' computed a non-positive scale ({scale}) for a {layout.Width}x{layout.Height} layout within {maxGridWorldWidth}x{maxGridWorldHeight} world units (preferredCellSize {preferredCellSize}, preferredGap {preferredGap}); aborting to avoid generating an invalid grid.", this);
                return false;
            }

            cellSize = preferredCellSize * scale;
            gap = preferredGap * scale;
            return true;
        }

        private void CreateSharedSprite()
        {
            _sharedTexture = new Texture2D(1, 1, TextureFormat.RGBA32, false)
            {
                filterMode = FilterMode.Point,
                wrapMode = TextureWrapMode.Clamp
            };
            _sharedTexture.SetPixel(0, 0, Color.white);
            _sharedTexture.Apply();

            _sharedSprite = Sprite.Create(
                _sharedTexture,
                new Rect(0f, 0f, 1f, 1f),
                new Vector2(0.5f, 0.5f),
                pixelsPerUnit: 1f);
        }

        private void GenerateGrid(PixelLayoutDefinition layout, float cellSize, float gap)
        {
            Width = layout.Width;
            Height = layout.Height;

            _cells = new PixelCell[Width, Height];
            _remainingPixelCount = 0;

            float spacing = cellSize + gap;
            float offsetX = (Width - 1) * spacing * 0.5f;
            float offsetY = (Height - 1) * spacing * 0.5f;

            for (int x = 0; x < Width; x++)
            {
                for (int y = 0; y < Height; y++)
                {
                    var localPosition = new Vector2(x * spacing - offsetX, y * spacing - offsetY);

                    var cellObject = new GameObject($"Pixel_{x}_{y}", typeof(PixelCell));
                    cellObject.transform.SetParent(transform, false);
                    cellObject.transform.localPosition = new Vector3(localPosition.x, localPosition.y, 0f);
                    cellObject.transform.localScale = new Vector3(cellSize, cellSize, 1f);

                    var spriteRenderer = cellObject.GetComponent<SpriteRenderer>();
                    spriteRenderer.sprite = _sharedSprite;

                    MatchTypeId matchTypeId = layout.GetMatchTypeId(x, y);
                    int matchId = layout.GetMatchId(x, y);
                    Color color = ResolvePixelColor(matchId);

                    var cell = cellObject.GetComponent<PixelCell>();
                    cell.Initialize(x, y, localPosition, matchTypeId, matchId, color);

                    _cells[x, y] = cell;
                    _remainingPixelCount++;
                }
            }
        }

        /// <summary>
        /// The single place a pixel's visible colour is ever resolved -
        /// directly from ColorPalette, the same permanent Match ID table
        /// CharacterDatabase resolves a collector's Character_XX prefab
        /// from. Never returns a null/undefined result: falls back to
        /// magenta with a logged error for any Match ID outside the
        /// approved 1-20 table, the same fallback shape every other
        /// resolver in this project uses (e.g. MonsterMaterialDatabase's
        /// predecessor, CharacterDatabase.GetPrefab).
        /// </summary>
        private static Color ResolvePixelColor(int matchId)
        {
            if (ColorPalette.TryGetByMatchId(matchId, out Color color))
                return color;

            Debug.LogError($"PixelGrid: no ColorPalette entry for Match ID {matchId}; falling back to magenta.");
            return Color.magenta;
        }

        private enum Side
        {
            Left,
            Right,
            Bottom,
            Top
        }

        /// <summary>
        /// Finds the active pixel of the given MatchTypeId closest to the
        /// supplied world-space position and consumes it. The candidate must be
        /// reachable, in a straight line, from the grid side the position is
        /// closest to (every cell between the candidate and that boundary must
        /// already be consumed) and must be aligned with the position along
        /// the perpendicular axis, within alignmentTolerance world units.
        /// Returns false if no matching pixel currently satisfies both.
        ///
        /// consumedWorldPosition/consumedColor report the consumed cell's own
        /// world position (read BEFORE Consume() disables it - a disabled
        /// GameObject's Transform.position stays valid and accurate, so this
        /// is not a race) and colour, for the sole current caller
        /// (PixelConsumer) to spawn a FoodPacket that starts exactly where
        /// the pixel visually was. Both are default/unset when this returns
        /// false - callers must not read them on failure.
        ///
        /// This consume is the sole moment a pixel is reserved: Consume()
        /// deactivates the cell and _remainingPixelCount decrements
        /// immediately, synchronously, right here - never deferred to
        /// whenever the resulting FoodPacket happens to arrive. That
        /// arrival-side delay is entirely a hunger-timing concern (see
        /// FoodFlightController), not a grid-state one; a consumed pixel can
        /// never be matched by this method again from this call onward,
        /// regardless of how long its FoodPacket then takes to fly.
        /// </summary>
        public bool TryConsumeNearestExposed(Vector3 worldPosition, MatchTypeId matchTypeId, float alignmentTolerance, out Vector3 consumedWorldPosition, out Color consumedColor)
        {
            Vector3 localPosition = transform.InverseTransformPoint(worldPosition);
            Side side = DetermineSide(localPosition);

            PixelCell best = null;
            float bestSqrDistance = float.MaxValue;

            for (int x = 0; x < Width; x++)
            {
                for (int y = 0; y < Height; y++)
                {
                    PixelCell cell = _cells[x, y];
                    if (cell == null || !cell.IsActive)
                        continue;

                    if (cell.MatchTypeId != matchTypeId)
                        continue;

                    if (!HasClearInwardPath(x, y, side))
                        continue;

                    if (!IsAligned(cell, side, localPosition, alignmentTolerance))
                        continue;

                    float sqrDistance = (cell.transform.position - worldPosition).sqrMagnitude;
                    if (sqrDistance < bestSqrDistance)
                    {
                        bestSqrDistance = sqrDistance;
                        best = cell;
                    }
                }
            }

            if (best == null)
            {
                consumedWorldPosition = default;
                consumedColor = default;
                return false;
            }

            // Read before Consume() (which only deactivates the GameObject,
            // never moves it) so callers always get the pixel's real launch
            // position even though the cell itself is inactive by the time
            // they use it.
            consumedWorldPosition = best.transform.position;
            consumedColor = best.PixelColor;

            // best was filtered to IsActive above, so Consume() here always
            // performs a real, first-time consumption — safe to decrement
            // exactly once per successful call, no rescan needed.
            best.Consume();
            _remainingPixelCount--;
            return true;
        }

        /// <summary>
        /// Picks the grid side the local position is closest to, normalizing by
        /// Width/Height so the comparison stays meaningful for non-square grids.
        /// </summary>
        private Side DetermineSide(Vector3 localPosition)
        {
            float normalizedX = Width > 0 ? localPosition.x / Width : localPosition.x;
            float normalizedY = Height > 0 ? localPosition.y / Height : localPosition.y;

            if (Mathf.Abs(normalizedX) >= Mathf.Abs(normalizedY))
                return localPosition.x >= 0f ? Side.Right : Side.Left;

            return localPosition.y >= 0f ? Side.Top : Side.Bottom;
        }

        /// <summary>
        /// From Top/Bottom the candidate must share the position's local x
        /// (horizontal alignment); from Left/Right it must share the local y
        /// (vertical alignment). This restricts consumption to the row or
        /// column currently facing the rider, so cells in other rows/columns —
        /// ahead, behind, or already passed — are never eligible until the
        /// rider aligns with them again.
        /// </summary>
        private bool IsAligned(PixelCell cell, Side side, Vector3 localPosition, float alignmentTolerance)
        {
            Vector2 localCellPosition = cell.LocalPosition;

            return side == Side.Top || side == Side.Bottom
                ? Mathf.Abs(localCellPosition.x - localPosition.x) <= alignmentTolerance
                : Mathf.Abs(localCellPosition.y - localPosition.y) <= alignmentTolerance;
        }

        /// <summary>
        /// True when every cell between (x, y) and the grid boundary on the
        /// given side is already consumed (or missing), so the straight path
        /// from that side to this cell is clear. A cell already adjacent to
        /// the boundary is always reachable.
        /// </summary>
        private bool HasClearInwardPath(int x, int y, Side side)
        {
            switch (side)
            {
                case Side.Left:
                    for (int i = 0; i < x; i++)
                    {
                        if (IsBlocking(i, y))
                            return false;
                    }
                    return true;

                case Side.Right:
                    for (int i = Width - 1; i > x; i--)
                    {
                        if (IsBlocking(i, y))
                            return false;
                    }
                    return true;

                case Side.Bottom:
                    for (int j = 0; j < y; j++)
                    {
                        if (IsBlocking(x, j))
                            return false;
                    }
                    return true;

                default: // Side.Top
                    for (int j = Height - 1; j > y; j--)
                    {
                        if (IsBlocking(x, j))
                            return false;
                    }
                    return true;
            }
        }

        private bool IsBlocking(int x, int y)
        {
            PixelCell cell = _cells[x, y];
            return cell != null && cell.IsActive;
        }

        private void OnDestroy()
        {
            if (_sharedSprite != null)
                Destroy(_sharedSprite);

            if (_sharedTexture != null)
                Destroy(_sharedTexture);
        }
    }
}
