using UnityEngine;

namespace Project001.Gameplay.Pixels
{
    /// <summary>
    /// Generates a centred 6x6 grid of PixelCell objects on Awake, using a single
    /// shared runtime-generated 1x1 sprite and a deterministic 3-colour pattern.
    /// </summary>
    public class PixelGrid : MonoBehaviour
    {
        private const int GridSize = 6;
        private const float CellSize = 1f;

        [SerializeField, Tooltip("Extra spacing added between neighbouring cells, in world units.")]
        [Min(0f)]
        private float cellGap = 0.05f;

        private static readonly Color[] Palette =
        {
            Color.red,
            Color.green,
            Color.blue
        };

        private Texture2D _sharedTexture;
        private Sprite _sharedSprite;
        private PixelCell[,] _cells;
        private int _remainingPixelCount;

        public int Width => GridSize;

        public int Height => GridSize;

        /// <summary>
        /// Number of pixels not yet consumed. Maintained incrementally —
        /// initialized once when the grid is generated and decremented
        /// exactly once per successful consumption. Never rescanned.
        /// </summary>
        public int RemainingPixelCount => _remainingPixelCount;

        /// <summary>
        /// True once every pixel generated by this grid has been consumed.
        /// Purely a state query — this class makes no gameplay decisions
        /// based on it.
        /// </summary>
        public bool IsComplete => _remainingPixelCount <= 0;

        private void Awake()
        {
            CreateSharedSprite();
            GenerateGrid();
        }

        private void CreateSharedSprite()
        {
            _sharedTexture = new Texture2D(1, 1, TextureFormat.RGBA32, false)
            {
                filterMode = FilterMode.Point,
                wrapMode = TextureWrapMode.Clamp
            };
            _sharedTexture.SetPixel(0, 0, Color.white);
            _sharedTexture.Apply();

            _sharedSprite = Sprite.Create(
                _sharedTexture,
                new Rect(0f, 0f, 1f, 1f),
                new Vector2(0.5f, 0.5f),
                pixelsPerUnit: 1f);
        }

        private void GenerateGrid()
        {
            _cells = new PixelCell[GridSize, GridSize];
            _remainingPixelCount = 0;

            float spacing = CellSize + cellGap;
            float offset = (GridSize - 1) * spacing * 0.5f;

            for (int x = 0; x < GridSize; x++)
            {
                for (int y = 0; y < GridSize; y++)
                {
                    var localPosition = new Vector2(x * spacing - offset, y * spacing - offset);

                    var cellObject = new GameObject($"Pixel_{x}_{y}", typeof(PixelCell));
                    cellObject.transform.SetParent(transform, false);
                    cellObject.transform.localPosition = new Vector3(localPosition.x, localPosition.y, 0f);
                    cellObject.transform.localScale = new Vector3(CellSize, CellSize, 1f);

                    var spriteRenderer = cellObject.GetComponent<SpriteRenderer>();
                    spriteRenderer.sprite = _sharedSprite;

                    var cell = cellObject.GetComponent<PixelCell>();
                    cell.Initialize(x, y, localPosition, Palette[(x + y) % Palette.Length]);

                    _cells[x, y] = cell;
                    _remainingPixelCount++;
                }
            }
        }

        private enum Side
        {
            Left,
            Right,
            Bottom,
            Top
        }

        /// <summary>
        /// Finds the active pixel of the given colour closest to the supplied
        /// world-space position and consumes it. The candidate must be
        /// reachable, in a straight line, from the grid side the position is
        /// closest to (every cell between the candidate and that boundary must
        /// already be consumed) and must be aligned with the position along
        /// the perpendicular axis, within alignmentTolerance world units.
        /// Returns false if no matching pixel currently satisfies both.
        /// </summary>
        public bool TryConsumeNearestExposed(Vector3 worldPosition, Color color, float alignmentTolerance)
        {
            Vector3 localPosition = transform.InverseTransformPoint(worldPosition);
            Side side = DetermineSide(localPosition);

            PixelCell best = null;
            float bestSqrDistance = float.MaxValue;

            for (int x = 0; x < Width; x++)
            {
                for (int y = 0; y < Height; y++)
                {
                    PixelCell cell = _cells[x, y];
                    if (cell == null || !cell.IsActive)
                        continue;

                    if (cell.PixelColor != color)
                        continue;

                    if (!HasClearInwardPath(x, y, side))
                        continue;

                    if (!IsAligned(cell, side, localPosition, alignmentTolerance))
                        continue;

                    float sqrDistance = (cell.transform.position - worldPosition).sqrMagnitude;
                    if (sqrDistance < bestSqrDistance)
                    {
                        bestSqrDistance = sqrDistance;
                        best = cell;
                    }
                }
            }

            if (best == null)
                return false;

            // best was filtered to IsActive above, so Consume() here always
            // performs a real, first-time consumption — safe to decrement
            // exactly once per successful call, no rescan needed.
            best.Consume();
            _remainingPixelCount--;
            return true;
        }

        /// <summary>
        /// Picks the grid side the local position is closest to, normalizing by
        /// Width/Height so the comparison stays meaningful for non-square grids.
        /// </summary>
        private Side DetermineSide(Vector3 localPosition)
        {
            float normalizedX = Width > 0 ? localPosition.x / Width : localPosition.x;
            float normalizedY = Height > 0 ? localPosition.y / Height : localPosition.y;

            if (Mathf.Abs(normalizedX) >= Mathf.Abs(normalizedY))
                return localPosition.x >= 0f ? Side.Right : Side.Left;

            return localPosition.y >= 0f ? Side.Top : Side.Bottom;
        }

        /// <summary>
        /// From Top/Bottom the candidate must share the position's local x
        /// (horizontal alignment); from Left/Right it must share the local y
        /// (vertical alignment). This restricts consumption to the row or
        /// column currently facing the rider, so cells in other rows/columns —
        /// ahead, behind, or already passed — are never eligible until the
        /// rider aligns with them again.
        /// </summary>
        private bool IsAligned(PixelCell cell, Side side, Vector3 localPosition, float alignmentTolerance)
        {
            Vector2 localCellPosition = cell.LocalPosition;

            return side == Side.Top || side == Side.Bottom
                ? Mathf.Abs(localCellPosition.x - localPosition.x) <= alignmentTolerance
                : Mathf.Abs(localCellPosition.y - localPosition.y) <= alignmentTolerance;
        }

        /// <summary>
        /// True when every cell between (x, y) and the grid boundary on the
        /// given side is already consumed (or missing), so the straight path
        /// from that side to this cell is clear. A cell already adjacent to
        /// the boundary is always reachable.
        /// </summary>
        private bool HasClearInwardPath(int x, int y, Side side)
        {
            switch (side)
            {
                case Side.Left:
                    for (int i = 0; i < x; i++)
                    {
                        if (IsBlocking(i, y))
                            return false;
                    }
                    return true;

                case Side.Right:
                    for (int i = Width - 1; i > x; i--)
                    {
                        if (IsBlocking(i, y))
                            return false;
                    }
                    return true;

                case Side.Bottom:
                    for (int j = 0; j < y; j++)
                    {
                        if (IsBlocking(x, j))
                            return false;
                    }
                    return true;

                default: // Side.Top
                    for (int j = Height - 1; j > y; j--)
                    {
                        if (IsBlocking(x, j))
                            return false;
                    }
                    return true;
            }
        }

        private bool IsBlocking(int x, int y)
        {
            PixelCell cell = _cells[x, y];
            return cell != null && cell.IsActive;
        }

        private void OnDestroy()
        {
            if (_sharedSprite != null)
                Destroy(_sharedSprite);

            if (_sharedTexture != null)
                Destroy(_sharedTexture);
        }
    }
}
