using UnityEngine;

namespace Project001.Gameplay.Presentation
{
    /// <summary>
    /// Classic theme gameplay background: a single SpriteRenderer, parented
    /// to Main Camera (see BootstrapSceneCreator.CreateGameplayBackground)
    /// so it always inherits the camera's own rotation exactly. Because the
    /// camera is orthographic, a quad parallel to it (identity local
    /// rotation, any local Z) always covers the exact same rectangle in
    /// camera-local space regardless of depth - orthographic projection has
    /// no perspective foreshortening - so unlike GameplayLayout.
    /// ComputeOrthographicSize's own height-fit term, this needs no
    /// separate correction for GameplayLayout.CameraTiltDegrees.
    ///
    /// Stays behind every other gameplay element via two independent
    /// guarantees, not one: its authored local Z (BootstrapSceneCreator's
    /// GameplayBackgroundLocalDepth, well beyond GameplayLayout.
    /// CameraDistance) places it behind every opaque 3D character for
    /// normal depth testing, and its dedicated "Background" Sorting Layer
    /// (first/lowest in Project Settings > Tags and Layers, every other
    /// SpriteRenderer in the project stays on "Default") places it behind
    /// every other SpriteRenderer (PixelGrid cells, WaitingSlot outlines,
    /// ConveyorPathRenderer) regardless of Z.
    ///
    /// Scales to always fully cover the visible viewport - crop, never
    /// stretch - using the exact same GameplayLayout.ComputeOrthographicSize
    /// this scene's camera fits to (see PortraitCameraFitter). Both are
    /// independently driven from the same Screen.width/height inputs, so
    /// this has no Awake-order dependency on PortraitCameraFitter and never
    /// reads the Camera component itself.
    ///
    /// Applies a small multiplicative tint (see tint below) to this
    /// SpriteRenderer's own colour - the simplest possible "configurable
    /// presentation-level dimming" seam (a Color property on the renderer
    /// this project already has), rather than a second overlay object, an
    /// extra Canvas, or a shader/material change. Background.png itself is
    /// never read, decoded, or regenerated by this - the multiply happens
    /// entirely at render time, on the GPU, per frame, so the source asset
    /// stays completely untouched. Deliberately still fully within "do not
    /// edit the source PNG": SpriteRenderer.color has always defaulted to
    /// opaque white (a 1x multiply, i.e. no visible effect) since this
    /// component was first added - this only assigns a different Color to
    /// that same existing, always-present property.
    /// </summary>
    [RequireComponent(typeof(SpriteRenderer))]
    public class GameplayBackground : MonoBehaviour
    {
        // Manual Unity review: Background.png read as slightly too bright/
        // saturated behind gameplay content, competing with characters,
        // PixelGrid, and white UI/frame elements instead of sitting behind
        // them. Target was ~8-12% dimming, "very slightly cool/neutral",
        // without desaturating toward gray or reading as dark/muddy.
        //
        // A flat scalar multiply (e.g. 0.90, 0.90, 0.90) would hit the
        // dimming target alone but is colour-neutral, not "slightly cool" -
        // and a multiply can only ever reduce a channel relative to the
        // others (it can never boost blue past the source pixel's own
        // value), so "cool" here means R and G pulled down a little further
        // than B, not B pushed up. R 0.895 / G 0.905 / B 0.915 - average
        // 0.905, i.e. 9.5% dimming, centred in the requested 8-12% range -
        // with only a +-0.01 spread around that average between channels,
        // deliberately small so the cast reads as "neutral, barely cool"
        // rather than an obvious blue tint, which would start desaturating
        // the source art's own pastel hues instead of just dimming them.
        // Because this is multiplicative (not a flat alpha overlay), every
        // channel keeps its own relative proportion to the others - the
        // pastel colours and the airy/light feel survive, just slightly
        // less bright, rather than being flattened toward one blended grey.
        //
        // A serialized field, not a hardcoded literal in Awake - "add a
        // configurable... mechanism", per this pass's own requirement -
        // editable/re-tunable directly in the Inspector without touching
        // this file again.
        [SerializeField, Tooltip("Multiplicative tint applied to this background sprite - the entire 'mute the background' mechanism (see class remarks). White (1,1,1,1) = no effect. Default dims ~9.5% with a barely-cool cast, chosen to separate gameplay content from the background without desaturating it.")]
        private Color tint = new Color(0.895f, 0.905f, 0.915f, 1f);

        private SpriteRenderer _spriteRenderer;

        private void Awake()
        {
            _spriteRenderer = GetComponent<SpriteRenderer>();
            _spriteRenderer.color = tint;
            Fit(Screen.width, Screen.height);
        }

        /// <summary>
        /// Uniformly scales this sprite so it fully covers a
        /// GameplayLayout.ComputeOrthographicSize viewport at the given
        /// screen size - the larger of the two axis scale factors, so the
        /// sprite's own aspect ratio is preserved (never stretched) and any
        /// excess extends past the visible frame - cropped by the camera's
        /// own edges, nothing else needed - rather than leaving a gap.
        /// Exposed (not just called from Awake), mirroring
        /// PortraitCameraFitter.Fit, so a future resize/orientation-change
        /// handler could call it again without duplicating this logic. A
        /// missing sprite or non-positive input is a silent no-op, the same
        /// "nothing to size yet" shape PortraitCameraFitter's own
        /// non-positive guard uses.
        /// </summary>
        public void Fit(float screenWidth, float screenHeight)
        {
            if (_spriteRenderer == null)
                _spriteRenderer = GetComponent<SpriteRenderer>();

            if (_spriteRenderer.sprite == null || screenWidth <= 0f || screenHeight <= 0f)
                return;

            float aspect = screenWidth / screenHeight;
            float orthoSize = GameplayLayout.ComputeOrthographicSize(screenWidth, screenHeight);
            float viewportWidth = orthoSize * 2f * aspect;
            float viewportHeight = orthoSize * 2f;

            Vector2 nativeSize = _spriteRenderer.sprite.bounds.size;
            if (nativeSize.x <= 0f || nativeSize.y <= 0f)
                return;

            float scale = Mathf.Max(viewportWidth / nativeSize.x, viewportHeight / nativeSize.y);
            transform.localScale = new Vector3(scale, scale, 1f);
        }
    }
}
